inputDir: "/mnt/disks/geb_storage/iseq/20220407_142243/Fastq"
outdir: "iseq_20220407_142243_aln40_singleEnd_batch"

single_end: false # treat paired end as single end

# Crispresso settings
amplicon_seq: "CTGACATTTCTCTTGTCTCCTCTgtgcccagggtgctggagaatccaaatgtcctctgatggtcaaagtcctggatgctgtccgaggcagccctgctgtagacgtggctgtaaaagtgttcaaaaagaccTCTGAGGGATCCTGGGAGC"
coding_seq: "atggcttcccttcgactcttcctcctttgcctcgctggactggtatttgtgtctgaagctggccccgcgggtgctggagaatccaaatgtcctctgatggtcaaagtcctggatgctgtccgaggcagccctgctgtagacgtggctgtaaaagtgttcaaaaagacctctgagggatcctgggagccctttgcctctgggaagaccgcggagtctggagagctgcacgggctcaccacagatgagaagtttgtagaaggagtgtacagagtagaactggacaccaaatcgtactggaagacacttggcatttccccgttccatgaattcgcggatgtggttttcacagccaacgactctggccatcgccactacaccatcgcagccctgctcagcccatactcctacagcaccacggctgtcgtcagcaacccccagaattga"
guide_seq: "ttacagccacgtctacagca"
crispresso_args: "--default_min_aln_score 40"
batch: true
